name: Python
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
      - uses: chartboost/ruff-action@v1
        with:
          args: check --extend-select I
